# Automatically generated file. DO NOT MODIFY. xD
#
# This file is generated by device/xiaomi/surya/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter davinci phoenix surya toco violet,$(TARGET_DEVICE)),)

endif
