# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm6150-common/setup-makefiles.sh
# This file is generated by device/xiaomi/surya/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter davinci phoenix surya toco violet,$(TARGET_DEVICE)),)

endif
